### ISSUE TITLE
Submit to F-Droid

### ISSUE THREAD

**Issue by etam** [tiagoshibata/Android-GPSd-Client#2]
Pretty please :)

https://f-droid.org/en/contribute/

**Comment by tiagoshibata** [comment]
I'll take a look at the project and submission process next week. Does it help if I provide APK somewhere instead? I might not want to package and submit it to more repositories.

**Comment by tiagoshibata** [comment]
I took a quick look at the project and don't feel like going through the submission process. I can provide compiled APKs at the GitHub releases page if that helps.

**Comment by etam** [comment]
Thanks for looking into that. Providing apks at github may also help. You could get it then on IzzyOnDroid repository https://gitlab.com/IzzyOnDroid/repo

**Comment by etam** [comment]
Is it OK if I open a "Request For Packaging" issue at https://gitlab.com/fdroid/rfp ?

**Comment by tiagoshibata** [comment]
Totally. If you need my permission you have it, just don't expect me to push it forward in their repo. I'm busy right now and not willing to keep up the app in more repositories.

I'll provide an APK in GitHub releases sometime in the future (probably within this week).

**Comment by IzzySoft** [comment]
@tiagoshibata could you create tags (one per release) please? That would make the update process easier for F-Droid. From a quick glance I see no problems for your app to make it into the main repo. If it unexpectedly doesn't make it, I gladly serve it via my repo. As the process until your app is listed in main might take a few weeks, be welcome to start with a tag right away, attach the `.apk` to it, and let me know. Usually takes less than a day for my repo :wink:

**Comment by tiagoshibata** [comment]
Awesome! I'm busy these days, but I'll do it when I have the time (probably this Saturday or Sunday). I'm happy to provide APKs in tags or releases (whatever is easier for the users) so people without the app store can use the app, I just don't want the commitment of updating it in multiple stores.

**Comment by IzzySoft** [comment]
@tiagoshibata as long as the APKs are attached to their corresponding tags/releases (at Github, these two are synonyms), my auto-updater can pick them – so no additional maintenance needed for an "additional store". For the "official F-Droid repo" ([RFP is here](https://gitlab.com/fdroid/rfp/issues/674)) it's similar: tags enable automated update checks, so the new version is built then (just remember to increase `versionCode` and `versionName` *before* creating the tag).

So as soon as you've created the tags, please let me know. I'd then adjust the RFP accordingly (update check method) – and, if there's an (signed) APK attached, pull it into my repo (as soon it's in the official repo, I'd remove it from mine to avoid confusion).

**Comment by licaon-kter** [comment]
@tiagoshibata 

`app/src/main/res/mipmap-ldpi` why isn't it named `.png` ? Where is it used?

**Comment by tiagoshibata** [comment]
That was probably my mistake when converting icon densities and moving files around. I'll fix that, thanks for catching it!

**Comment by tiagoshibata** [comment]
@licaon-kter it's fixed now.

@IzzySoft I created a release for v1.0.1. I have a few questions about your needs:

* Should the APK be signed?
* Any special needs (debug symbols?)

The APK in this release is signed with my store credentials and in release mode. Let me know if I should change something.

**Comment by licaon-kter** [comment]
F-Droid compiles and signs its own.

After F-Droid pick it up, @IzzySoft will drop it from his repo

**Comment by IzzySoft** [comment]
As @licaon-kter wrote. But it is not yet in mine :wink: So for my repo:

* signed: yes, please!
* debug symbols etc.: no. It's for the end user, so that's not required.

The currently attached APK does not "work out":

    ERROR: No signing certificates found in repo/io.github.tiagoshibata.gpsdclient_1.0.1.apk
    WARNING: Skipping 'io.github.tiagoshibata.gpsdclient_1.0.1.apk' with invalid signature!

**Comment by tiagoshibata** [comment]
So, no more action from my part, just keeping pushing tags for each release?

**Comment by IzzySoft** [comment]
Above error still exists. For the official repo: yes, keep creating tags for each new version. For my repo you'd need to provide a signed APK. If you want to skip my repo and just wait until your app turns up in the official one, that's of course fine with me – just let me know then so I stop checking :wink:

**Comment by tiagoshibata** [comment]
Okay, I understand you now :smiley: . Which build/signing configuration should I use? I used release with full APK signature (the newer method). Should I sign with the older method instead? Screenshot attached.

![2018-08-07-00 19 33-screenshot](https://user-images.githubusercontent.com/5521887/43789618-44060c6e-9a25-11e8-8238-b940520ace25.png)

**Comment by IzzySoft** [comment]
I'm not a dev, so I cannot tell for sure. I can deal with v1 and v2 AFAIK, IMHO you could even sign with both at the same time. Let me know when you've attached an APK, I'll check it then ASAP.

**Comment by licaon-kter** [comment]
Older Android versions might not accept V2 BTW, use both.

**Comment by tiagoshibata** [comment]
I updated the APK to use both signature versions.Let me know if it works.

https://github.com/tiagoshibata/Android-GPSd-Client/releases/download/v1.0.1/Android-GPSd-Client.apk

**Comment by tiagoshibata** [comment]
Okay, I updated the APK to use both signature versions. Let me know how it goes.

https://github.com/tiagoshibata/Android-GPSd-Client/releases/download/v1.0.1/Android-GPSd-Client.apk

**Comment by IzzySoft** [comment]
Indirect answer: https://apt.izzysoft.de/fdroid/index/apk/io.github.tiagoshibata.gpsdclient

Direct answer: Works :wink: :+1: :fireworks:
